const express = require("express");
const dotenv = require("dotenv");
const { connectDB } = require("./config/db");
dotenv.config();
const userRoutes = require("./routes/userRoutes");
const port = process.env.PORT || 5000;
connectDB();
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use("/api/users", userRoutes);
app.get("/", (req, res) => res.send("API running"));
app.listen(port, () => console.log(`Server Started on Port:${port}`));
